[[annotation]]
file = "/Volumes/T9/herita-project/input_data/dbNSFP5.3a_grch38_lite.tsv.gz"
columns = [1, 2, 3, 4, 19, 20, 21, 22, 23, 24, 25]
names = ["dbNSFP_chr", "dbNSFP_pos", "dbNSFP_ref", "dbNSFP_alt", "MetaRNN_score", "REVEL_score", "PrimateAI_score", "ClinPred_score", "ESM1b_score", "AlphaMissense_score", "CADD_phred"]
ops = ["self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self"]
